### PR TITLE
Adding pollution limit line to Indian data

### PR DESCRIPTION
**Pull request by karukes**
Solving issue #121 
The final result looks like that 

PM2 5_forecast_comparison_plot_multi_20230128_225817_full

### CODE REVIEW

**Comment by swhustla** [comment]
Looks very good. One slight change would be to add some explanation of each item ("India" and "WHO") with an asterisk and comment under the plot. e.g. with the units, acronym W.H.O. explanation and the fact that these are recommended values. See the Economist example.

**Comment by swhustla** [comment]
Referring to #142

**Review by swhustla — COMMENTED** [review]
Refer to my comments on PR - some explanation of "India" and "WHO" required in addition. Thanks.

**Review by swhustla — APPROVED** [review]

**Comment by swhustla** [comment]
@karukes I have made some changes; to make it more generic and improve plotting across many cities. Let me know what you think.

**Comment by karukes** [comment]
@swhustla It looks good, I will merge it.

**Pull request merged**
